package com.agustinbravop.clinica_odontologica.odontologo;

import com.agustinbravop.clinica_odontologica.dto.OdontologoDTO;
import com.agustinbravop.clinica_odontologica.service.OdontologoService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class OdontologoServiceTest {

    @Autowired
    private OdontologoService odontologoService;

    private OdontologoDTO getSampleOdontologoDTO() {
        OdontologoDTO odontoDTO = new OdontologoDTO();
        odontoDTO.setNombre("Agustín");
        odontoDTO.setApellido("Bravo");
        odontoDTO.setMatricula(54321);
        return odontoDTO;
    }

    @Test
    public void create_SampleOdontologoDTO_AutogeneratedIdNotNull() {
        OdontologoDTO odontologoDTO = odontologoService.create(getSampleOdontologoDTO());
        Assertions.assertNotNull(odontologoDTO.getId());
    }
}
